export { Home } from './home'
export { About } from './about'
export { Projects } from './projects'
export { Contact } from './contact'
export { Blog } from './blog'
export { Feedback } from './feedback'
